### ISSUE TITLE
启动应用出现exception，见详细信息

### ISSUE THREAD

**Issue by ups216** [smallidea/repos#3]
Exception has occurred: CLR/System.Data.SqlClient.SqlException
An exception of type 'System.Data.SqlClient.SqlException' occurred in System.Data.SqlClient.dll but was not handled in user code: 'String or binary data would be truncated in table 'Repos1.dbo.AllRepos', column 'Name'. Truncated value: 'AspNet.Security.OAuth.Provider'.
The statement has been terminated.'
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Repos.Lib.SqlHelper.executeNonQuery(SqlConnection connection, SqlTransaction transaction, CommandType commandType, String commandText, SqlParameter[] parms) in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Lib/SqlHelper.cs:line 414
   at Repos.Lib.SqlHelper.ExecuteNonQuery(SqlConnection connection, CommandType commandType, String commandText, SqlParameter[] parms) in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Lib/SqlHelper.cs:line 382
   at Repos.Lib.SqlHelper.ExecuteNonQuery(String connectionString, CommandType commandType, String commandText, SqlParameter[] parms) in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Lib/SqlHelper.cs:line 367
   at Repos.Lib.SqlHelper.ExecuteNonQuery(String commandText, SqlParameter[] parms) in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Lib/SqlHelper.cs:line 69
   at Repos.Controllers.HomeController.insertRpos4Db(List`1 list) in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Controllers/HomeController.cs:line 169
   at Repos.Controllers.HomeController.GetData() in /Users/leixu/source/repos/github.com/ups216/repos/Repos/Controllers/HomeController.cs:line 63
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by ups216** [comment]
![image](https://user-images.githubusercontent.com/1203500/71256909-37a21d00-236d-11ea-8f20-631fc8e76fd0.png)

**Comment by smallidea** [comment]
String or binary data would be truncated in table 'Repos1.dbo.AllRepos'

字段长度设置有问题，api中的字符串长度超出了数据库varchar字段设置的长度。
是因为两份database.sql导致的，您可能使用了repos文件下的database.sql，使用最新的database.sql创建数据库即可。

**Comment by ups216** [comment]
这个问题仍然存在，我在azure devops中给你创建了issue，这里可以关闭了。

https://dev.azure.com/leansoftx/Chenxiaoping_CT/_workitems/edit/116
